import { createElement } from '@lwc/engine-dom';
import GetPicklistValuesByRecordTypeAdapter from 'c/getPicklistValuesByRecordTypeAdapter';

describe('c-get-picklist-values-by-record-type-adapter', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-get-picklist-values-by-record-type-adapter', {
            is: GetPicklistValuesByRecordTypeAdapter
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});